#ddev-generated

http:
  routers:
    
    
    backend-simplified-web-80-http:
      
      rule: HostRegexp(`backend-simplified.ddev.site`)
      
      service: "backend-simplified-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    backend-simplified-web-8025-http:
      
      rule: HostRegexp(`backend-simplified.ddev.site`)
      
      service: "backend-simplified-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    
    
    
    
    backend-simplified-web-80-https:
      
      rule: HostRegexp(`backend-simplified.ddev.site`)
      
      service: "backend-simplified-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    backend-simplified-web-8025-https:
      
      rule: HostRegexp(`backend-simplified.ddev.site`)
      
      service: "backend-simplified-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    

  services:
    
    backend-simplified-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-backend-simplified-web:80
    
    backend-simplified-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-backend-simplified-web:8025
    
    backend-simplified-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-backend-simplified-web:80
    
    backend-simplified-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-backend-simplified-web:8025
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/backend-simplified.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/backend-simplified.key

